cask_args appdir: '/Applications'

tap 'homebrew/cask'
tap 'homebrew/core'
tap 'homebrew/bundle'

#programming
brew 'python'
brew 'node'

brew 'coreutils'
brew 'openssl'
brew 'readline'
brew 'mas' # for brew to install app store apps
brew 'wget'


#shell
# brew 'zsh' # comes with macos
brew 'zsh-syntax-highlighting'
brew 'zsh-autosuggestions'
brew 'htop'
brew 'neofetch'
brew 'tmux'
brew 'vim'

cask 'google-chrome'
cask 'visual-studio-code'
cask 'appcleaner'
cask 'dozer'
cask 'discord'
cask 'notion'
cask 'microsoft-teams'
cask 'microsoft-outlook'


cask 'parallels'
cask 'parsec'
cask 'iina'


mas "magnet", id: 441258766
